quiz_2/idea_factory/config/routes.rb
Rails.application.routes.draw do
  get 'home/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ideas
  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  get '/', to: "home#new"
end

quiz_2/idea_factory/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    alias_action :create, :read, :update, :destroy, to: :crud

    can(:crud, Idea) do |idea|
      idea.user == user
    end
    
    can :crud, Review do |review|
      review.user == user
    end  

    can :like, Idea do |idea|
      idea.user != user
    end
  end
end

quiz_2/idea_factory/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

quiz_2/idea_factory/app/models/idea.rb
class Idea < ApplicationRecord
    has_many :reviews, dependent: :destroy
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user
    validates :title, presence: true, uniqueness: true
    validates :description, presence: true
end

quiz_2/idea_factory/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates :idea_id, uniqueness: {scope: :user_id}
end

quiz_2/idea_factory/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :idea
    belongs_to :user
    validates :body, presence: true
end

quiz_2/idea_factory/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :ideas, dependent: :nullify
    has_many :reviews, dependent: :nullify
    has_many :likes, dependent: :destroy
    has_many :liked_ideas, through: :likes, source: :idea

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: true, format: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

    def full_name
        "#{first_name} #{last_name}"
    end
end

quiz_2/idea_factory/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def authenticate!
        redirect_to new_session_path, alert: "Sign In First!" unless user_signed_in?
    end
end

quiz_2/idea_factory/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def new
  end
end

quiz_2/idea_factory/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    before_action :find_id, only: [:show, :destroy, :edit, :update]
    before_action :authenticate!, except: [:show, :index]
    before_action :authorize!, only: [:destroy, :edit, :update]
    def new
        @idea = Idea.new
    end

    def create
        @idea = Idea.new idea_params
        @idea.user = current_user
        if @idea.save
            redirect_to @idea, notice: "New idea submitted!"
        else
            render :new, alert: "Unable to create a new idea!"
        end
    end

    def index
        @ideas = Idea.order(created_at: :desc)
    end

    def show
        @review = Review.new
    end
    
    def destroy
        @idea.destroy
        redirect_to ideas_path, notice: "Idea deleted!"
    end
    
    def edit
    end
    
    def update
        if @idea.update idea_params
            redirect_to @idea, notice: "Idea Updated!"
        else
            redirect_to ideas_path, alert: "Unable to update your idea. Try again!"
        end
    end

    private

    def idea_params
        params.require(:idea).permit(:title, :description)
    end

    def find_id
        @idea = Idea.find params[:id]
    end

    def authorize!
        redirect_to ideas_path, alert: "Not Authorized!" unless can? :crud, @idea
    end
end

quiz_2/idea_factory/app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_id
    before_action :authenticate!
    before_action :like!

    def create
        @like = Like.new(user_id: current_user.id, idea_id: @idea.id )
        if @like.save
            redirect_to @idea, notice: "Liked"
        else
            redirect_to ideas_path, notice: "Try again!"
        end
    end

    def destroy
        @like = @idea.likes.find_by(user_id: current_user.id)
        @like.destroy
        redirect_to @idea, notice: "Unliked"
    end

    private

    def find_id
        @idea = Idea.find params[:idea_id]
    end

    def like!
        redirect_to ideas_path, alert: "You can't like/un-like your own idea!" unless can? :like, @idea
    end
end

quiz_2/idea_factory/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate!

    def create    
        @idea = Idea.find params[:idea_id]
        @review = Review.new review_params
        @review.user = current_user
        @review.idea = @idea
        if @review.save
            redirect_to idea_path(@review.idea_id), notice: "Thank you for the review!"
        else
            render 'ideas/show', alert: "Unable to create a review! Try again."
        end
    end

    def destroy
        @review = Review.find params[:id]
        if can? :crud, @review
            @review.destroy
            redirect_to idea_path(@review.idea_id), notice: "Review deleted!"
        else
            redirect_to ideas_path, alert: "Not Authorized!"
        end
    end

    private

    def review_params
        params.require(:review).permit(:body)
    end
end

quiz_2/idea_factory/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user&.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to ideas_path, notice: "Signed In!"
        else
            render :new, alert: "Try again!"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to ideas_path, notice: "Signed Out!"
    end

    private
end

quiz_2/idea_factory/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        if @user.save
            session[:user_id] = @user.id
            redirect_to ideas_path, notice: "Welcome!"
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

quiz_2/idea_factory/app/helpers/application_helper.rb
module ApplicationHelper
end

quiz_2/idea_factory/app/helpers/home_helper.rb
module HomeHelper
end

quiz_2/idea_factory/app/helpers/ideas_helper.rb
module IdeasHelper
end

quiz_2/idea_factory/app/helpers/likes_helper.rb
module LikesHelper
end

quiz_2/idea_factory/app/helpers/reviews_helper.rb
module ReviewsHelper
end

quiz_2/idea_factory/app/helpers/sessions_helper.rb
module SessionsHelper
end

quiz_2/idea_factory/app/helpers/users_helper.rb
module UsersHelper
end

quiz_2/idea_factory/app/views/home/new.html.erb
<h1 class='title'>Share Your Idea</h1>

quiz_2/idea_factory/app/views/ideas/_form.html.erb
<div class="layout">
<% if @idea.errors.any? %>
    <ul>
        <% @idea.errors.full_messages.each do |error|%>
            <li><%= error%></li>
        <% end %>
    </ul>
<% end %>

    <%= form_with model: @idea, local: true do |form| %>
        <div class="text-field">
            <div class='label'><%= form.label :title%></div>
            <%= form.text_field :title%>
        </div>
        <div class="text-field">
            <div class='label'><%= form.label :description%></div>
            <%= form.text_area :description%>
        </div>
        <div class="button"><%= form.submit%></div>
    <% end %>
</div>

quiz_2/idea_factory/app/views/ideas/edit.html.erb
<h1 class="title">Update your Idea</h1>

<%= render "form"%>

quiz_2/idea_factory/app/views/ideas/index.html.erb
<div class='layout'>
    <% @ideas.each do |idea|%>
        <h1><%= link_to idea.title, idea_path(idea.id)%></h1>
        <p><%= idea.description%></p>
        <div>
            <p><%= idea.user.full_name%>'s idea with <%= idea.likers.count%> likes</p>
        </div>
        <hr/>    
    <% end %>
</div>

quiz_2/idea_factory/app/views/ideas/new.html.erb
<h1 class='title'>New Idea</h1>

<%= render "form"%>

quiz_2/idea_factory/app/views/ideas/show.html.erb
<div class="layout">
    <h1><%=@idea.title%></h1>
    <p><%=@idea.description%></p>
    <small>Posted by <%= @idea.user.full_name %> <%= time_ago_in_words(@idea.created_at)%></small>

    <div class='edit delete'>
        <%= link_to "Edit", edit_idea_path(@idea)%> | 
        <%= link_to "Delete", idea_path(@idea), method: :delete, data: {confirm: "Are you sure you want to delete your post?"}%>
    </div>

    <% liker = @idea.likes.find_by(user: current_user)%>
    <% if liker.present? %>
        <%= link_to "👎", idea_like_path(@idea, liker), method: :delete%>
    <% else %>
        <%= link_to "👍", idea_likes_path(@idea), method: :post%>
    <% end %>
    <small><%= @idea.likers.count%> people like this idea</small>

    <h2>Review this idea</h2>
    <%= form_with model: [@idea, @review], local: true do |form| %>
        <% if @review.errors.any? %>
            <ul>
                <% @review.errors.full_messages.each do |error|%>
                    <li><%= error%></li>
                <% end %>
            </ul>
        <% end %>

        <div>
            <%=form.label :body%>
            <%= form.text_area :body%>
        </div>
        <div class="button"><%= form.submit%></div>
    <% end %>

    <% @idea.reviews.each do |review|%>
        <p><%= review.body%></p>
        <small>Reviewed by <%= review.user.full_name %> <%= time_ago_in_words(review.created_at)%> | <%= link_to "Delete", idea_review_path(review.idea_id, review), method: :delete, data: {confirm: "Are you sure you want to delete your review?"}%></small>
    <% end %>
</div>

quiz_2/idea_factory/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaFactory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class='nav-bar'>
      <div><%= link_to image_tag("https://how.us.org/wp-content/uploads/2018/08/idea6.png", class: 'logo'), ideas_path%></div>
      <%= flash[:notice] || flash[:alert]%>

      <span class='sub-navigation'>

        <div class='panel'>
          <div><%= link_to "New Idea", new_idea_path%> |</div>
          <% if user_signed_in? %>
            <p>Hello, <%= current_user.full_name%></p> |
            <p><%= link_to "Sign Out", session_path(current_user), method: :delete, data: {confirm: "Do you want to sign out?"}, class: 'sub-panel'%></p> |
          <% else %>
            <p><%= link_to "Sign Up", new_user_path, class: 'sub-panel'%></p> |
            <p><%= link_to "Sign In", new_session_path, class: 'sub-panel'%></p> 
        <% end %>
        </div>
      </span>
    </div>

    <%= yield %>
  </body>
</html>

quiz_2/idea_factory/app/views/users/new.html.erb
<div class='layout'>
    <h1>Make a New Account</h1>

    <%= form_with model: @user, local: true do |form|%>
        <% if @user.errors.any? %>
            <ul>
                <% @user.errors.full_messages.each do |error|%>
                    <li><%= error%></li>
                <% end %>
            </ul>
        <% end %>

        <div class='text-field'>
            <%= form.label :first_name%>
            <%= form.text_field :first_name%>
        </div>
        <div class='text-field'>
            <%= form.label :last_name%>
            <%= form.text_field :last_name%>
        </div>
        <div class='text-field'>
            <%= form.label :email%>
            <%= form.email_field :email%>
        </div>
        <div class='text-field'>
            <%= form.label :password%>
            <%= form.password_field :password%>
        </div>
        <div class='text-field'>
            <%= form.label :password_confirmation%>
            <%= form.password_field :password_confirmation%>
        </div>
        <div class='button'><%= form.submit%></div>
    <% end %>
</div>